remote_theme: pages-themes/minimal@v0.2.0
plugins: 

title: Muhammad Afreed - Cybersecurity Professional
description: A dedicated cybersecurity professional with a focus on protecting digital assets.
